### ISSUE TITLE
Publish 0.1.2 to hex.pm?

### ISSUE THREAD

**Issue by randycoulman** [ludwikbukowski/telemetry_influxdb#11]
Do you have a timeframe for publishing the tagged 0.1.2 release to hex.pm?  We'd like to be able to pull from there rather than GitHub if possible.

Thanks again for working through the big v2 support PR with us and getting that in!

**Comment by ludwikbukowski** [comment]
Hey, I've just published it under tag 0.2.0!
sorry for a delay; I was busy with Code Beam and trying back home with all coronavirus chaos around.

Once again thanks for your input!
