### ISSUE TITLE
Increase event throughput to InfluxDB

### ISSUE THREAD

**Issue by marcdel** [ludwikbukowski/telemetry_influxdb#13]
Hi there 👋🏻,

I'm working with a team over at InfluxData that's using and has contributed to this library in the past. We're at the point now where we're sending so many events that they're stacking up and the workers aren't able to process them quickly enough to get through the whole queue.

I don't know if you had anything in mind around this, but one idea we had was to send events to InfluxDB in batches rather than one at a time. Here's a quick spike on what that batching process could look like: https://github.com/marcdel/batch_reporter_spike/blob/master/lib/batch_reporter.ex

We'd be happy to work on a PR if that's something you're open to!

**Comment by ludwikbukowski** [comment]
Hey @marcdel !
Sure, the idea of sending events in batches was something I had in mind for future development :)
I would _highly_ appreciate any PRs!
However, I would keep it configurable.
If you need any help, let me know!
