### ISSUE TITLE
InfluxDB 2.0 support

### ISSUE THREAD

**Issue by randycoulman** [ludwikbukowski/telemetry_influxdb#5]
Thanks so much for creating this library! Looks like a really nice solution.

We'd like to be able to use it for an internal project that is using InfluxDB 2.0, but it currently supports only the 1.x API.  The 2.0 API is a bit different (see https://v2.docs.influxdata.com/v2.0/api/#operation/PostWrite).

Ideally, this reporter would work with both InfluxDB 1.x and 2.0 to make it easier for people to upgrade to 2.0, and we're willing to do the work to make this happen.  We'd like some direction from you before we go too far down the wrong road, though.

1. Is 2.0 support something you're interested in for this library?
2. If so, do you have any thoughts about what you'd like that to look like or how you'd like it structured?

At a high level, here's what we think needs to be done.  There's probably more that we're not thinking of just yet.

- The v2 API takes a `bucket` and one of `org` or `orgID` as params instead of the `db` param that 1.x takes.  This will affect configuration, validation, and URL construction.  The line protocol has not changed, so the payload format should work as-is.

- UDP support is now done through a [Telegraf plugin](https://github.com/influxdata/telegraf/blob/release-1.13/plugins/inputs/socket_listener/README.md) and does not support binding to a specific bucket/org as near as I can tell.  So a UDP request would need to include that information somehow.  This looks like the biggest change at first glance.

Disclaimer: I work for InfluxData, but I'm still relatively new and learning the APIs, so I may not have all the details right here.

**Comment by ludwikbukowski** [comment]
Hey!

Thanks for your interest!
Indeed there is a lack of support for 2.0.
I will check all the differences and be back to you shortly!
Do you say that it should be possible to implement 2.0 API keeping all the backward compatibility for 1.0 ?

**Comment by randycoulman** [comment]
I just started working on this, but it looks like the HTTP API should be relatively easy to port.  There'll be a few different config options and (I think) just a change to the URL to POST to.

I think UDP support will be more work, but I haven't got to the bottom of that yet.  I'll probably start with a PR that adds 2.0 support for HTTP only, if that's OK with you.

**Comment by ludwikbukowski** [comment]
yep, all contributions are more than welcome!
