### ISSUE TITLE
No metadata passed

### ISSUE THREAD

**Issue by samuelebistoletti** [ludwikbukowski/telemetry_influxdb#6]
Hi,
is there a way to pass telemetry events metadata to influxDB? I need also to gather some data from there and save into InfluxDB.

**Comment by samuelebistoletti** [comment]
I will open a merge request for that, I'm testing it now, seems working.

**Comment by ludwikbukowski** [comment]
Okay, thanks!

**Comment by samuelebistoletti** [comment]
> Okay, thanks!

You are welcome! If everything is ok, can you please release an update on Hex for the new version?

**Comment by samuelebistoletti** [comment]
Thank you for merging that, since it's a feature now I'll close the issue.

**Comment by ludwikbukowski** [comment]
Hey @samuelebistoletti
your work is already exposed in a release:
https://github.com/ludwikbukowski/telemetry_influxdb/releases/tag/0.1.1 !

Thank you once again !

**Comment by samuelebistoletti** [comment]
Thanks! I noticed that you released the new version under 0.1.1 tag, and I realized that I pushed a mix file version during the pull request with an error in version bump: during tests I set 0.2.0 on `@version` variable, and 0.1.1 under project version.

Any plan to release the new version on Hex.pm?

Thanks

**Comment by ludwikbukowski** [comment]
Yep, I am just working on that, dont worry.
I am planning to release new version on Hex ASAP (today)

**Comment by ludwikbukowski** [comment]
done
